import type { ActivityLogEntry, Manager, Subject } from "../types";

const HOUR = 60 * 60 * 1000;
const now = Date.now();
const isoFromHoursAgo = (h: number) => new Date(now - h * HOUR).toISOString();

export const ORG_NAME: string = "◯◯区役所 福祉課";

export const SUBJECTS: Subject[] = [
  {
    id: "S-2024-0001",
    name: "田中 花子",
    age: 82,
    gender: "F",
    district: "桜町1丁目",
    addressDetail: "桜町1-12-3 シティハイム301",
    emergencyContactName: "田中 健 (長男)",
    emergencyContactPhone: "090-2341-9981",
    caseworker: "山田 美咲",
    lastCheckIn: isoFromHoursAgo(53),
    hoursSinceLastCheckIn: 53,
    status: "danger",
    note: "糖尿病・高血圧。先週 通院記録あり。",
  },
  {
    id: "S-2024-0002",
    name: "佐藤 一郎",
    age: 77,
    gender: "M",
    district: "桜町3丁目",
    addressDetail: "桜町3-8-8 ひかりマンション504",
    emergencyContactName: "佐藤 順子 (妹)",
    emergencyContactPhone: "090-4422-7710",
    caseworker: "山田 美咲",
    lastCheckIn: isoFromHoursAgo(50),
    hoursSinceLastCheckIn: 50,
    status: "danger",
    note: "独居。携帯電話の接続切れが頻繁。",
  },
  {
    id: "S-2024-0003",
    name: "鈴木 美智子",
    age: 75,
    gender: "F",
    district: "桃ヶ丘2丁目",
    addressDetail: "桃ヶ丘2-2-2 グリーンハイツA-201",
    emergencyContactName: "鈴木 賢吾 (甥)",
    emergencyContactPhone: "090-7788-1290",
    caseworker: "中村 翔",
    lastCheckIn: isoFromHoursAgo(36),
    hoursSinceLastCheckIn: 36,
    status: "warn",
  },
  {
    id: "S-2024-0004",
    name: "高橋 健",
    age: 79,
    gender: "M",
    district: "桃ヶ丘5丁目",
    addressDetail: "桃ヶ丘5-13-0 サンシャイン1号",
    emergencyContactName: "高橋 明子 (義妹)",
    emergencyContactPhone: "090-3344-5566",
    caseworker: "中村 翔",
    lastCheckIn: isoFromHoursAgo(28),
    hoursSinceLastCheckIn: 28,
    status: "warn",
  },
  {
    id: "S-2024-0005",
    name: "渡辺 久子",
    age: 70,
    gender: "F",
    district: "桜町1丁目",
    addressDetail: "桜町1-5-1 さくら連棟101",
    emergencyContactName: "渡辺 大輔 (長男)",
    emergencyContactPhone: "090-9911-2233",
    caseworker: "山田 美咲",
    lastCheckIn: isoFromHoursAgo(25),
    hoursSinceLastCheckIn: 25,
    status: "warn",
  },
  {
    id: "S-2024-0006",
    name: "伊藤 正",
    age: 84,
    gender: "M",
    district: "桃ヶ丘1丁目",
    addressDetail: "桃ヶ丘1-7 戸建",
    emergencyContactName: "伊藤 ゆかり (長女)",
    emergencyContactPhone: "090-2200-3300",
    caseworker: "中村 翔",
    lastCheckIn: isoFromHoursAgo(6),
    hoursSinceLastCheckIn: 6,
    status: "safe",
  },
  {
    id: "S-2024-0007",
    name: "山本 千代",
    age: 73,
    gender: "F",
    district: "桜町2丁目",
    addressDetail: "桜町2-50 青葉マンション205-1102",
    emergencyContactName: "山本 翔太 (長男)",
    emergencyContactPhone: "090-7770-8881",
    caseworker: "山田 美咲",
    lastCheckIn: isoFromHoursAgo(2),
    hoursSinceLastCheckIn: 2,
    status: "safe",
  },
  {
    id: "S-2024-0008",
    name: "中村 一夫",
    age: 81,
    gender: "M",
    district: "桃ヶ丘4丁目",
    addressDetail: "桃ヶ丘4-200 新春ビル4F",
    emergencyContactName: "中村 さやか (長女)",
    emergencyContactPhone: "090-5544-3322",
    caseworker: "中村 翔",
    lastCheckIn: isoFromHoursAgo(0.5),
    hoursSinceLastCheckIn: 0.5,
    status: "safe",
  },
  {
    id: "S-2024-0009",
    name: "小林 弘子",
    age: 78,
    gender: "F",
    district: "桜町4丁目",
    addressDetail: "桜町4-77 むくげハイツ102",
    emergencyContactName: "小林 修 (長男)",
    emergencyContactPhone: "090-1212-3434",
    caseworker: "山田 美咲",
    lastCheckIn: isoFromHoursAgo(11),
    hoursSinceLastCheckIn: 11,
    status: "safe",
  },
  {
    id: "S-2024-0010",
    name: "加藤 たつ子",
    age: 86,
    gender: "F",
    district: "桃ヶ丘3丁目",
    addressDetail: "桃ヶ丘3-15 ひだまりむら203",
    emergencyContactName: "加藤 正弘 (長男)",
    emergencyContactPhone: "090-9090-1212",
    caseworker: "中村 翔",
    lastCheckIn: isoFromHoursAgo(20),
    hoursSinceLastCheckIn: 20,
    status: "safe",
  },
  {
    id: "S-2024-0011",
    name: "吉田 政義",
    age: 76,
    gender: "M",
    district: "桜町5丁目",
    addressDetail: "桜町5-200 戸建",
    emergencyContactName: "吉田 由美 (長女)",
    emergencyContactPhone: "090-6677-8899",
    caseworker: "山田 美咲",
    lastCheckIn: isoFromHoursAgo(4),
    hoursSinceLastCheckIn: 4,
    status: "safe",
  },
  {
    id: "S-2024-0012",
    name: "斎藤 明子",
    age: 80,
    gender: "F",
    district: "桃ヶ丘2丁目",
    addressDetail: "桃ヶ丘2-50 青葉連棟103",
    emergencyContactName: "斎藤 英樹 (長男)",
    emergencyContactPhone: "090-2233-4455",
    caseworker: "中村 翔",
    lastCheckIn: isoFromHoursAgo(8),
    hoursSinceLastCheckIn: 8,
    status: "safe",
  },
];

export const DASHBOARD_STATS = {
  total: 124,
  danger: SUBJECTS.filter((s) => s.status === "danger").length,
  warn: SUBJECTS.filter((s) => s.status === "warn").length,
  safe:
    124 -
    SUBJECTS.filter((s) => s.status === "danger").length -
    SUBJECTS.filter((s) => s.status === "warn").length,
  primaryDistrictTotal: 68,
  secondaryDistrictTotal: 56,
};

export const MANAGERS: Manager[] = [
  {
    id: "M-001",
    department: "◯◯区役所 福祉課",
    position: "課長",
    name: "佐藤 健一",
    phone: "03-1234-5678",
    email: "kensato@city.oo.lg.jp",
    role: "admin",
    approvalStatus: "approved",
    joinedAt: "2024-09-01",
  },
  {
    id: "M-002",
    department: "桜町地域包括支援センター",
    position: "主任",
    name: "山田 美咲",
    phone: "03-2345-6789",
    email: "myamada@city.oo.lg.jp",
    role: "supervisor",
    approvalStatus: "approved",
    joinedAt: "2024-09-12",
  },
  {
    id: "M-003",
    department: "桃ヶ丘地域包括支援センター",
    position: "主任",
    name: "中村 翔",
    phone: "03-3456-7890",
    email: "snakamura@city.oo.lg.jp",
    role: "supervisor",
    approvalStatus: "approved",
    joinedAt: "2024-09-15",
  },
  {
    id: "M-004",
    department: "◯◯区社会福祉協議会",
    position: "社会福祉士",
    name: "井上 結衣",
    phone: "03-4567-8901",
    email: "yinoue@oo-shakyo.or.jp",
    role: "worker",
    approvalStatus: "approved",
    joinedAt: "2024-10-04",
  },
  {
    id: "M-005",
    department: "◯◯区社会福祉協議会",
    position: "社会福祉士",
    name: "藤井 雄大",
    phone: "03-5678-9012",
    email: "yfujii@oo-shakyo.or.jp",
    role: "worker",
    approvalStatus: "approved",
    joinedAt: "2024-10-22",
  },
  {
    id: "M-006",
    department: "桜町地域包括支援センター",
    position: "事務補助",
    name: "大塚 拓也",
    phone: "03-6789-0123",
    email: "totsuka@city.oo.lg.jp",
    role: "viewer",
    approvalStatus: "pending",
    joinedAt: "2026-04-29",
  },
  {
    id: "M-007",
    department: "桃ヶ丘地域包括支援センター",
    position: "ケースワーカー",
    name: "野口 さやか",
    phone: "03-7890-1234",
    email: "snoguchi@city.oo.lg.jp",
    role: "worker",
    approvalStatus: "pending",
    joinedAt: "2026-05-02",
  },
  {
    id: "M-008",
    department: "◯◯区社会福祉協議会",
    position: "社会福祉士",
    name: "川口 浩二",
    phone: "03-8901-2345",
    email: "kkawaguchi@oo-shakyo.or.jp",
    role: "worker",
    approvalStatus: "suspended",
    joinedAt: "2024-08-11",
  },
];

export const ACTIVITY_LOG: ActivityLogEntry[] = [
  {
    id: "L-1001",
    type: "alert",
    subjectName: "田中 花子",
    district: "桜町1丁目",
    message: "48時間未確認 — 緊急通知を自動送信 (担当: 山田)",
    occurredAt: isoFromHoursAgo(0.2),
    severity: "danger",
  },
  {
    id: "L-1002",
    type: "alert",
    subjectName: "佐藤 一郎",
    district: "桜町3丁目",
    message: "48時間未確認 — 緊急通知を自動送信 (担当: 山田)",
    occurredAt: isoFromHoursAgo(2),
    severity: "danger",
  },
  {
    id: "L-1003",
    type: "call",
    subjectName: "鈴木 美智子",
    district: "桃ヶ丘2丁目",
    message: "緊急連絡先(甥)へ通話完了 — 家族訪問予定",
    actor: "中村 翔",
    occurredAt: isoFromHoursAgo(3.4),
    severity: "warn",
  },
  {
    id: "L-1004",
    type: "checkin",
    subjectName: "山本 千代",
    district: "桜町2丁目",
    message: "安否チェックイン完了",
    occurredAt: isoFromHoursAgo(2),
    severity: "safe",
  },
  {
    id: "L-1005",
    type: "visit",
    subjectName: "高橋 健",
    district: "桃ヶ丘5丁目",
    message: "現地訪問対応完了 — 健康異常なしを確認",
    actor: "井上 結衣",
    occurredAt: isoFromHoursAgo(5),
    severity: "warn",
  },
  {
    id: "L-1006",
    type: "checkin",
    subjectName: "伊藤 正",
    district: "桃ヶ丘1丁目",
    message: "安否チェックイン完了",
    occurredAt: isoFromHoursAgo(6),
    severity: "safe",
  },
  {
    id: "L-1007",
    type: "register",
    subjectName: "斎藤 明子",
    district: "桃ヶ丘2丁目",
    message: "新規対象者登録 (CSV一括アップロード)",
    actor: "藤井 雄大",
    occurredAt: isoFromHoursAgo(22),
    severity: "safe",
  },
];

export const DISTRICT_BREAKDOWN = [
  { name: "桜町1丁目", total: 18, danger: 1, warn: 1, response: 89 },
  { name: "桜町2丁目", total: 22, danger: 0, warn: 0, response: 100 },
  { name: "桜町3丁目", total: 15, danger: 1, warn: 0, response: 93 },
  { name: "桜町4丁目", total: 12, danger: 0, warn: 0, response: 100 },
  { name: "桜町5丁目", total: 10, danger: 0, warn: 0, response: 100 },
  { name: "桃ヶ丘1丁目", total: 14, danger: 0, warn: 0, response: 100 },
  { name: "桃ヶ丘2丁目", total: 11, danger: 0, warn: 1, response: 91 },
  { name: "桃ヶ丘3丁目", total: 9, danger: 0, warn: 0, response: 100 },
  { name: "桃ヶ丘4丁目", total: 8, danger: 0, warn: 0, response: 100 },
  { name: "桃ヶ丘5丁目", total: 5, danger: 0, warn: 1, response: 80 },
];
