import type { ActivityLogEntry, Manager, Subject } from "../types";

const HOUR = 60 * 60 * 1000;
const now = Date.now();
const isoFromHoursAgo = (h: number) => new Date(now - h * HOUR).toISOString();

export const ORG_NAME: string = "OO구청 복지정책과";

export const SUBJECTS: Subject[] = [
  {
    id: "S-2024-0001",
    name: "김복순",
    age: 82,
    gender: "F",
    district: "행복동 1통",
    addressDetail: "행복로 12, 신성빌라 301호",
    emergencyContactName: "김영수 (자녀)",
    emergencyContactPhone: "010-2341-9981",
    caseworker: "박지영",
    lastCheckIn: isoFromHoursAgo(53),
    hoursSinceLastCheckIn: 53,
    status: "danger",
    note: "당뇨/고혈압. 1주일 전 병원 방문 기록 있음.",
  },
  {
    id: "S-2024-0002",
    name: "이만수",
    age: 77,
    gender: "M",
    district: "행복동 3통",
    addressDetail: "행복로 88, 한빛아파트 102동 504호",
    emergencyContactName: "이순자 (누이)",
    emergencyContactPhone: "010-4422-7710",
    caseworker: "박지영",
    lastCheckIn: isoFromHoursAgo(50),
    hoursSinceLastCheckIn: 50,
    status: "danger",
    note: "독거. 휴대전화 연결 잦은 끊김.",
  },
  {
    id: "S-2024-0003",
    name: "정순옥",
    age: 75,
    gender: "F",
    district: "안심동 2통",
    addressDetail: "안심로 22, 푸른빌라 가동 201호",
    emergencyContactName: "정현우 (조카)",
    emergencyContactPhone: "010-7788-1290",
    caseworker: "최민호",
    lastCheckIn: isoFromHoursAgo(36),
    hoursSinceLastCheckIn: 36,
    status: "warn",
  },
  {
    id: "S-2024-0004",
    name: "박길동",
    age: 79,
    gender: "M",
    district: "안심동 5통",
    addressDetail: "안심로 130, 햇살주택 1호",
    emergencyContactName: "박명자 (처제)",
    emergencyContactPhone: "010-3344-5566",
    caseworker: "최민호",
    lastCheckIn: isoFromHoursAgo(28),
    hoursSinceLastCheckIn: 28,
    status: "warn",
  },
  {
    id: "S-2024-0005",
    name: "한영자",
    age: 70,
    gender: "F",
    district: "행복동 1통",
    addressDetail: "행복로 5, 행복연립 101호",
    emergencyContactName: "한도현 (자녀)",
    emergencyContactPhone: "010-9911-2233",
    caseworker: "박지영",
    lastCheckIn: isoFromHoursAgo(25),
    hoursSinceLastCheckIn: 25,
    status: "warn",
  },
  {
    id: "S-2024-0006",
    name: "최광식",
    age: 84,
    gender: "M",
    district: "안심동 1통",
    addressDetail: "안심로 7, 단독주택",
    emergencyContactName: "최은정 (자녀)",
    emergencyContactPhone: "010-2200-3300",
    caseworker: "최민호",
    lastCheckIn: isoFromHoursAgo(6),
    hoursSinceLastCheckIn: 6,
    status: "safe",
  },
  {
    id: "S-2024-0007",
    name: "윤정희",
    age: 73,
    gender: "F",
    district: "행복동 2통",
    addressDetail: "행복로 50, 청실아파트 205동 1102호",
    emergencyContactName: "윤상현 (자녀)",
    emergencyContactPhone: "010-7770-8881",
    caseworker: "박지영",
    lastCheckIn: isoFromHoursAgo(2),
    hoursSinceLastCheckIn: 2,
    status: "safe",
  },
  {
    id: "S-2024-0008",
    name: "조병철",
    age: 81,
    gender: "M",
    district: "안심동 4통",
    addressDetail: "안심로 200, 새봄빌딩 4층",
    emergencyContactName: "조수민 (자녀)",
    emergencyContactPhone: "010-5544-3322",
    caseworker: "최민호",
    lastCheckIn: isoFromHoursAgo(0.5),
    hoursSinceLastCheckIn: 0.5,
    status: "safe",
  },
  {
    id: "S-2024-0009",
    name: "오현주",
    age: 78,
    gender: "F",
    district: "행복동 4통",
    addressDetail: "행복로 77, 무궁화빌라 102호",
    emergencyContactName: "오재훈 (자녀)",
    emergencyContactPhone: "010-1212-3434",
    caseworker: "박지영",
    lastCheckIn: isoFromHoursAgo(11),
    hoursSinceLastCheckIn: 11,
    status: "safe",
  },
  {
    id: "S-2024-0010",
    name: "강달자",
    age: 86,
    gender: "F",
    district: "안심동 3통",
    addressDetail: "안심로 15, 햇빛마을 203호",
    emergencyContactName: "강민호 (자녀)",
    emergencyContactPhone: "010-9090-1212",
    caseworker: "최민호",
    lastCheckIn: isoFromHoursAgo(20),
    hoursSinceLastCheckIn: 20,
    status: "safe",
  },
  {
    id: "S-2024-0011",
    name: "임정규",
    age: 76,
    gender: "M",
    district: "행복동 5통",
    addressDetail: "행복로 200, 단독주택",
    emergencyContactName: "임수연 (자녀)",
    emergencyContactPhone: "010-6677-8899",
    caseworker: "박지영",
    lastCheckIn: isoFromHoursAgo(4),
    hoursSinceLastCheckIn: 4,
    status: "safe",
  },
  {
    id: "S-2024-0012",
    name: "서명희",
    age: 80,
    gender: "F",
    district: "안심동 2통",
    addressDetail: "안심로 50, 푸른연립 103호",
    emergencyContactName: "서영민 (자녀)",
    emergencyContactPhone: "010-2233-4455",
    caseworker: "최민호",
    lastCheckIn: isoFromHoursAgo(8),
    hoursSinceLastCheckIn: 8,
    status: "safe",
  },
];

export const DASHBOARD_STATS = {
  total: 124,
  danger: SUBJECTS.filter((s) => s.status === "danger").length,
  warn: SUBJECTS.filter((s) => s.status === "warn").length,
  safe:
    124 -
    SUBJECTS.filter((s) => s.status === "danger").length -
    SUBJECTS.filter((s) => s.status === "warn").length,
  primaryDistrictTotal: 68,
  secondaryDistrictTotal: 56,
};

export const MANAGERS: Manager[] = [
  {
    id: "M-001",
    department: "OO구청 복지정책과",
    position: "과장",
    name: "한정민",
    phone: "02-1234-5678",
    email: "jmhan@oo.go.kr",
    role: "admin",
    approvalStatus: "approved",
    joinedAt: "2024-09-01",
  },
  {
    id: "M-002",
    department: "행복동 주민센터",
    position: "주무관",
    name: "박지영",
    phone: "02-2345-6789",
    email: "jypark@oo.go.kr",
    role: "supervisor",
    approvalStatus: "approved",
    joinedAt: "2024-09-12",
  },
  {
    id: "M-003",
    department: "안심동 주민센터",
    position: "주무관",
    name: "최민호",
    phone: "02-3456-7890",
    email: "mhchoi@oo.go.kr",
    role: "supervisor",
    approvalStatus: "approved",
    joinedAt: "2024-09-15",
  },
  {
    id: "M-004",
    department: "OO구 종합사회복지관",
    position: "사회복지사",
    name: "이서연",
    phone: "02-4567-8901",
    email: "sylee@oo-welfare.or.kr",
    role: "worker",
    approvalStatus: "approved",
    joinedAt: "2024-10-04",
  },
  {
    id: "M-005",
    department: "OO구 종합사회복지관",
    position: "사회복지사",
    name: "정우진",
    phone: "02-5678-9012",
    email: "wjjeong@oo-welfare.or.kr",
    role: "worker",
    approvalStatus: "approved",
    joinedAt: "2024-10-22",
  },
  {
    id: "M-006",
    department: "행복동 주민센터",
    position: "사회복무요원",
    name: "오태경",
    phone: "02-6789-0123",
    email: "tkoh@oo.go.kr",
    role: "viewer",
    approvalStatus: "pending",
    joinedAt: "2026-04-29",
  },
  {
    id: "M-007",
    department: "안심동 주민센터",
    position: "주무관",
    name: "노수정",
    phone: "02-7890-1234",
    email: "sjnoh@oo.go.kr",
    role: "worker",
    approvalStatus: "pending",
    joinedAt: "2026-05-02",
  },
  {
    id: "M-008",
    department: "OO구 종합사회복지관",
    position: "사회복지사",
    name: "강현우",
    phone: "02-8901-2345",
    email: "hwkang@oo-welfare.or.kr",
    role: "worker",
    approvalStatus: "suspended",
    joinedAt: "2024-08-11",
  },
];

export const ACTIVITY_LOG: ActivityLogEntry[] = [
  {
    id: "L-1001",
    type: "alert",
    subjectName: "김복순",
    district: "행복동 1통",
    message: "48시간 미확인 — 위급 알림 자동 발송 (담당: 박지영)",
    occurredAt: isoFromHoursAgo(0.2),
    severity: "danger",
  },
  {
    id: "L-1002",
    type: "alert",
    subjectName: "이만수",
    district: "행복동 3통",
    message: "48시간 미확인 — 위급 알림 자동 발송 (담당: 박지영)",
    occurredAt: isoFromHoursAgo(2),
    severity: "danger",
  },
  {
    id: "L-1003",
    type: "call",
    subjectName: "정순옥",
    district: "안심동 2통",
    message: "긴급 연락처(조카) 통화 완료 — 가족 방문 예정",
    actor: "최민호",
    occurredAt: isoFromHoursAgo(3.4),
    severity: "warn",
  },
  {
    id: "L-1004",
    type: "checkin",
    subjectName: "윤정희",
    district: "행복동 2통",
    message: "안부 체크인 완료",
    occurredAt: isoFromHoursAgo(2),
    severity: "safe",
  },
  {
    id: "L-1005",
    type: "visit",
    subjectName: "박길동",
    district: "안심동 5통",
    message: "현장 방문 조치 완료 — 건강 이상 없음 확인",
    actor: "이서연",
    occurredAt: isoFromHoursAgo(5),
    severity: "warn",
  },
  {
    id: "L-1006",
    type: "checkin",
    subjectName: "최광식",
    district: "안심동 1통",
    message: "안부 체크인 완료",
    occurredAt: isoFromHoursAgo(6),
    severity: "safe",
  },
  {
    id: "L-1007",
    type: "register",
    subjectName: "서명희",
    district: "안심동 2통",
    message: "신규 대상자 등록 (CSV 일괄 업로드)",
    actor: "정우진",
    occurredAt: isoFromHoursAgo(22),
    severity: "safe",
  },
];

export const DISTRICT_BREAKDOWN = [
  { name: "행복동 1통", total: 18, danger: 1, warn: 1, response: 89 },
  { name: "행복동 2통", total: 22, danger: 0, warn: 0, response: 100 },
  { name: "행복동 3통", total: 15, danger: 1, warn: 0, response: 93 },
  { name: "행복동 4통", total: 12, danger: 0, warn: 0, response: 100 },
  { name: "행복동 5통", total: 10, danger: 0, warn: 0, response: 100 },
  { name: "안심동 1통", total: 14, danger: 0, warn: 0, response: 100 },
  { name: "안심동 2통", total: 11, danger: 0, warn: 1, response: 91 },
  { name: "안심동 3통", total: 9, danger: 0, warn: 0, response: 100 },
  { name: "안심동 4통", total: 8, danger: 0, warn: 0, response: 100 },
  { name: "안심동 5통", total: 5, danger: 0, warn: 1, response: 80 },
];
